"""Presentation only: renders the Rust demand review without engineering calculations."""
import json,html,pathlib
root=pathlib.Path(__file__).parent
r=json.loads((root/'design-demand-review.json').read_text());p=json.loads((root/'UKR01-generated.json').read_text());esc=lambda x:html.escape(str(x))
rows=''.join(f'<tr><td>{esc(c["caseId"])}</td><td>{esc(c["resultId"])}</td><td>{c["maximumNodalTranslation"]["magnitude"]*1000:.3f} mm at {esc(c["maximumNodalTranslation"]["nodeId"])}</td><td>Converged</td></tr>' for c in r['cases'])
sections=''.join(f'<li>{esc(x["name"])}</li>' for x in p['sections'])
parts=[]
for c in r['cases']:
 members=''
 for m in c['physicalMembers']:
  cells=''.join(f'<td>{d["value"]/1000:.2f}<small>{esc(d["memberId"])} · x/L {d["station"]:.4f}</small></td>' for d in m['demands'])
  members+=f'<tr><td>{esc(m["name"])}<small>{esc(m["physicalMemberId"])}</small></td>{cells}</tr>'
 foundations=''.join('<tr><td>'+esc(f['supportId'])+'</td>'+''.join(f'<td>{v/1000:.2f}</td>' for v in f['foundationActions'])+'<td>INDETERMINATE</td></tr>' for f in c['foundations'])
 parts.append(f'<details><summary>{esc(c["caseId"])} — member demands and foundation actions</summary><p>Scalar maxima are separate observations, not one combined action vector. Values kN and kN m. Full simultaneous vectors and provenance are in the JSON review.</p><table><tr><th>Physical object</th><th>N</th><th>Vy</th><th>Vz</th><th>T</th><th>My</th><th>Mz</th></tr>{members}</table><h3>Foundation applied actions (opposite support reactions)</h3><table><tr><th>Support</th><th>Fx</th><th>Fy</th><th>Fz</th><th>Mx</th><th>My</th><th>Mz</th><th>Contact</th></tr>{foundations}</table></details>')
body=f'''<!doctype html><html lang="en"><meta charset="utf-8"><title>UKR01 residential reference — preliminary analysis</title><style>body{{font:16px/1.6 system-ui;color:#24394c;background:#f2f5f7;margin:0}}main{{max-width:1200px;margin:auto;padding:44px}}h1{{font-size:38px;line-height:1.2}}.tag{{color:#925500;font-weight:700}}section,details{{background:white;border:1px solid #dbe2e7;border-radius:12px;padding:24px;margin:20px 0}}table{{border-collapse:collapse;width:100%;font-size:13px}}td,th{{padding:10px;text-align:left;border-bottom:1px solid #dde4eb}}small{{display:block;color:#667788;font-size:11px}}summary{{cursor:pointer;font-weight:700}}code{{overflow-wrap:anywhere}}img{{width:100%;border-radius:8px}}@media print{{body{{background:white}}main{{padding:0}}details{{break-before:page}}}}</style><main><p class="tag">PRELIMINARY REFERENCE · SYNTHETIC INPUTS · DESIGN UNSUPPORTED</p><h1>Four-storey concrete residential frame</h1><p>British / UK Eurocodes intended · 12 × 12 m · ground + three upper storeys · flat roof at 12 m</p><section><img src="visible-frame.png" alt="Actual Structural Workbench model"><p>{len(p['nodes'])} analytical nodes · {len(p['members'])} frame/strip elements · 12 trial pad footings · stairs and intermediate landings</p></section><section><h2>Analysis completed; resistance design incomplete</h2><p>Eight real Rust/WASM linear elastic cases are checked against independent OpenSees results. All resistance checks remain UNSUPPORTED. Ground contact and settlement have not been solved. Trial dimensions must not be used as a construction design.</p><table><tr><th>Case</th><th>Exact result</th><th>Maximum nodal translation</th><th>Analysis</th></tr>{rows}</table><p><b>Nodal translations are not maximum beam/slab deflections.</b> Interior member displacement, cracking, creep, serviceability limits and long-term response need separate checks.</p></section><section><h2>Trial sections</h2><ul>{sections}</ul><h2>Saved model assumptions</h2><p>{esc(r['assumptions'])}</p></section><section><h2>Work required before design acceptance</h2><ul>{''.join('<li>'+esc(x)+'</li>' for x in r['requiredDesignWork'])}</ul><p><a href="UKR01-generated.json">Download project</a> · <a href="design-demand-review.json">Download exact demand review</a> · <a href="reference-numerical.json">Numerical verification</a></p><p>Model hash <code>{esc(r['modelHash'])}</code><br>Structure hash <code>{esc(r['structureHash'])}</code></p></section>{''.join(parts)}</main></html>'''
(root/'residential-review.html').write_text(body)
