#!/usr/bin/env python3
"""Regenerate crates/design/data/aisc-v16-subset.json from the held AISC
Shapes Database v16.0 (R-STEEL-SHAPES-V16, resources/private, not committed).

Standard library only. US customary columns as published; the workbench
converts to SI in crates/design/src/native.rs. Usage:

    python3 -I tools/extract-aisc-shapes.py resources/private/aisc-shapes-database-v16.xlsx
"""
import hashlib
import json
import re
import sys
import zipfile
import xml.etree.ElementTree as ET

NS = {"m": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
# The M07 subset plus the beams and supports of the AISC Design Examples v16
# single-plate connections (II.A-17A, II.A-17B, II.A-18, II.A-19A) and common
# UK-sized companions.
SHAPES = [
    "W24X62", "W18X50", "W14X132", "W14X99", "W8X21",
    "W16X50", "W14X90", "W16X36", "W18X35", "W21X62", "W12X26", "W10X33",
    # Composite beams of Design Examples I.1 and I.2 (M17).
    "W21X50", "W24X76",
]
# Output key → database column.
COLUMNS = [
    ("A", "A"), ("d", "d"), ("tw", "tw"), ("bf", "bf"), ("tf", "tf"),
    ("rx", "rx"), ("ry", "ry"), ("Zx", "Zx"), ("Zy", "Zy"), ("Sx", "Sx"),
    ("Sy", "Sy"), ("Ix", "Ix"), ("Iy", "Iy"), ("J", "J"),
    ("bf/2tf", "bf/2tf"), ("h/tw", "h/tw"), ("kdes", "kdes"), ("T", "T"),
]


def col_index(ref):
    letters = re.match(r"[A-Z]+", ref).group(0)
    n = 0
    for ch in letters:
        n = n * 26 + ord(ch) - 64
    return n - 1


def rows(path):
    z = zipfile.ZipFile(path)
    strings = [
        "".join(t.text or "" for t in si.iter("{%s}t" % NS["m"]))
        for si in ET.fromstring(z.read("xl/sharedStrings.xml")).findall("m:si", NS)
    ]
    sheet = ET.fromstring(z.read("xl/worksheets/sheet2.xml"))
    for row in sheet.find("m:sheetData", NS):
        out = {}
        for c in row.findall("m:c", NS):
            v = c.find("m:v", NS)
            if v is None:
                continue
            out[col_index(c.get("r"))] = strings[int(v.text)] if c.get("t") == "s" else v.text
        if out:
            yield [out.get(i) for i in range(max(out) + 1)]


def number(text):
    value = float(text)
    return int(value) if value == int(value) and abs(value) >= 1 and "." not in text else value


def main(path):
    sha = hashlib.sha256(open(path, "rb").read()).hexdigest()
    it = rows(path)
    header = next(it)
    # The worksheet repeats every column for SI; the first occurrence is US.
    index = {}
    for i, name in enumerate(header):
        if name and name not in index:
            index[name] = i
    found = {}
    for r in it:
        label = r[index["AISC_Manual_Label"]] if index["AISC_Manual_Label"] < len(r) else None
        if label in SHAPES:
            found[label] = {"designation": label, **{k: number(r[index[c]]) for k, c in COLUMNS}}
    missing = [s for s in SHAPES if s not in found]
    if missing:
        sys.exit(f"missing shapes: {missing}")
    out = {
        "id": "aisc-shapes-v16.0-subset-1",
        "source": "AISC Shapes Database v16.0, Database v16.0 worksheet; US customary columns; generated by tools/extract-aisc-shapes.py",
        "sourceSha256": sha,
        "shapes": [found[s] for s in SHAPES],
    }
    print(json.dumps(out, indent=2))


if __name__ == "__main__":
    main(sys.argv[1])
